shortcuts:
    start: [Enter]
    pause: [Space]
    resume: [Space]
    restart: [Ctrl+R]
    reset: [Enter]
    clear: [Ctrl+Enter]
    step: [Ctrl+Right]

    resize: []
    undo: [Ctrl+Z]
    redo: [Ctrl+Y, Ctrl+Shift+Z]
    save: [Ctrl+Shift+S]
    new: [Ctrl+N]
    update: [Ctrl+S]
    load: [Ctrl+O]
    close: [Ctrl+W]

    deselect: [Esc]
    delete: [Backspace, Delete]
    copy: [Ctrl+C]
    cut: [Ctrl+X]
    paste: [Ctrl+V]
    rotate: [R]
    flip_horizontal: []
    flip_vertical: []

    nudge_left: [Left, Shift+Left]
    nudge_right: [Right, Shift+Right]
    nudge_up: [Up, Shift+Up]
    nudge_down: [Down, Shift+Down]

colors:
    transparent: [0, 0, 0, 0]
    background: [0.1, 0.1, 0.1, 1]
    contrast: [0.16, 0.16, 0.16, 1]
    hover: [1, 1, 1, 0.2]
    text: [0.8, 0.8, 0.8, 1]

imgui_style:
    WindowBg: background
    Border: contrast
    
    FrameBg: contrast
    FrameBgHovered: hover

    Text: text

    Button: contrast
    ButtonHovered: hover
    
    CheckMark: text

    SliderGrab: hover

    Header: contrast
    HeaderActive: contrast
    
    TitleBg: contrast
    TitleBgActive: contrast
    
    Tab: transparent
    TabSelectedOverline: transparent
    TabDimmedSelected: transparent
    TabHovered: transparent
    TabUnfocused: transparent
    TabDimmed: transparent
    TabSelected: transparent