shortcuts:
    start: [Enter]
    pause: [Space]
    resume: [Space]
    restart: [Ctrl+R]
    reset: [Enter]
    clear: [Ctrl+Enter]
    step: [Right]
    resize: []

colors:
    transparent: [0, 0, 0, 0]
    background: [0.1, 0.1, 0.1, 1]
    contrast: [0.16, 0.16, 0.16, 1]
    hover: [1, 1, 1, 0.2]
    text: [0.8, 0.8, 0.8, 1]

imgui-style:
    WindowBg: background
    Border: contrast
    
    FrameBg: contrast
    FrameBgHovered: hover

    Text: text
    
    Button: contrast
    ButtonHovered: hover
    
    SliderGrab: hover

    Header: contrast
    HeaderActive: contrast
    
    TitleBg: contrast
    TitleBgActive: contrast
    
    Tab: transparent
    TabSelectedOverline: transparent
    TabDimmedSelected: transparent
    TabHovered: transparent
    TabUnfocused: transparent
    TabDimmed: transparent
    TabSelected: transparent